
###############################################################################
# This base workflow can be used in any repository that builds and pushes
# a docker image to AWS ECR. Additional steps can be added that test the code
# contained within the image before building the image to ensure code works. 

# Add secrets to Github Actions
###############################################################################

name: build-push-azure
on:
  push:
    branches:
      - main
jobs:
  build-images:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Azure Container Registry
        uses: azure/docker-login@v1
        with:
          registry: ${{ secrets.AZURE_REGISTRY }}
          username: ${{ secrets.ACR_USERNAME }}
          password: ${{ secrets.ACR_PASSWORD }}

      - name: Build & Push to ACR
        uses: docker/build-push-action@v2
        env: 
          IMAGE_TAG: latest
        with:
          push: true
          build-args: |
            version=${{ steps.tag.output.tag }}
          tags: ${{ secrets.AZURE_REGISTRY }}/${{ env.IMAGE_TAG}}